### ISSUE TITLE
Docker Compose file

### ISSUE THREAD

**Issue by nathanweeks** [18F/uswds-jekyll#189]
This suggestion might be beyond the scope of this repo, but it could be useful to add a [Docker Compose](https://docs.docker.com/compose/) file to allow non-Ruby & Jekyll experts (like myself) to quickly deploy a suitable software environment and start local jekyll development server.

E.g., given the following docker-compose.yaml in the root of the git repo working tree:
```
version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.0
    volumes:
      - ./:/srv/jekyll
      - jekyll-cache:/usr/local/bundle
    command: jekyll serve --incremental
    ports:
      - "4000:4000"

volumes:
  jekyll-cache:
```
`docker-compose up` will start a local jekyll server (pulling a container image that was built from the [jekyll/jekyll](https://github.com/envygeeks/jekyll-docker) git repo) that is exposed on port 4000. Missing gems are installed and cached in a docker volume to speed subsequent startups.
