### ISSUE TITLE
Add sub navigation option for sidenav

### ISSUE THREAD

**Issue by line47** [18F/uswds-jekyll#55]
Currently if you set the sidenav to the primary set of links which contains nested links the sub links do not show and sub links are only rendered in the top nav. I would expect the sidenav to render the same nested elements as the top navigation. 

This is loosely related to the PR put in by @AminPIC https://github.com/18F/uswds-jekyll/pull/52, I'd love to pull some functionality from the guides-style for rendering sub nav links.
- https://github.com/18F/guides-style/blob/master/_includes/sidebar.html
- https://github.com/18F/guides-style/blob/master/_includes/sidebar-children.html
- https://github.com/18F/guides-style#selectively-expanding-navigation-bar-items

### Screenshot
![screen shot 2017-10-30 at 11 30 25 am](https://user-images.githubusercontent.com/1449852/32179442-c93a6b2a-bd65-11e7-9539-cd40988e114b.png)
### Navigation code
```
primary:
  - text: Documentation
    href: /docs/
  - text: Navigation section
    links:
      - text: Demo link A
        href: /two/a/
      - text: Demo link B
        href: /two/b/
      - text: Demo link C
        href: /two/c/
  - text: Referenced section
    links: footer
  - text: External link
    href: https://18f.gsa.gov
```
